language: node_js
cache:
  - bundler
node_js:
  - "10"
before_install:
  - rvm use 2.6.3 --install --fuzzy
  - ./gitclone.sh
install:
  - bundle install
  - npm install
script:
  - grunt build
after_success:
  - ./gitpush.sh