language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
  - "6"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - PATH="/bin:$PATH" rvm use 2.6.3 --install --fuzzy
  - ./gitclone.sh
install:
  - bundle install
  - npm install
script:
  - grunt build
after_success:
  - ./gitpush.sh